// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticlesList: typeof import('./components/Interface/articles/ArticlesList.vue')['default']
    ArticleTile: typeof import('./components/Interface/articles/ArticleTile.vue')['default']
    BaseCategoryTag: typeof import('./components/Interface/BaseCategoryTag.vue')['default']
    BaseTitle: typeof import('./components/Interface/BaseTitle.vue')['default']
    CategoryMenu: typeof import('./components/sections/popular/CategoryMenu.vue')['default']
    Editors: typeof import('./components/sections/editorPick/Editors.vue')['default']
    EditorsTile: typeof import('./components/sections/editorPick/EditorsTile.vue')['default']
    Favorite: typeof import('./components/sections/Favorite.vue')['default']
    Footer: typeof import('./components/sections/Footer.vue')['default']
    Popular: typeof import('./components/sections/popular/Popular.vue')['default']
    Promo: typeof import('./components/sections/promo/Promo.vue')['default']
    PromoSlide: typeof import('./components/sections/promo/PromoSlide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/Interface/TheHeader.vue')['default']
    XContainer: typeof import('./components/Interface/XContainer.vue')['default']
  }
}
