// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    articlesTiles: typeof import('./components/sections/popular/articlesTiles.vue')['default']
    ArticlesTiles: typeof import('./components/sections/popular/ArticlesTiles.vue')['default']
    articleTile: typeof import('./components/sections/popular/articleTile.vue')['default']
    ArticleTile: typeof import('./components/sections/popular/ArticleTile.vue')['default']
    ArticleTiles: typeof import('./components/sections/popular/ArticleTiles.vue')['default']
    BaseCategoryTag: typeof import('./components/Interface/BaseCategoryTag.vue')['default']
    BaseTitle: typeof import('./components/Interface/BaseTitle.vue')['default']
    BlogsTiles: typeof import('./components/sections/popular/BlogsTiles.vue')['default']
    BlogTile: typeof import('./components/sections/popular/BlogTile.vue')['default']
    CategoryMenu: typeof import('./components/sections/popular/CategoryMenu.vue')['default']
    Popular: typeof import('./components/sections/popular/Popular.vue')['default']
    Promo: typeof import('./components/sections/promo/Promo.vue')['default']
    PromoSlide: typeof import('./components/sections/promo/PromoSlide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/Interface/TheHeader.vue')['default']
    TheXContainer: typeof import('./components/Interface/TheXContainer.vue')['default']
    TilesList: typeof import('./components/sections/popular/TilesList.vue')['default']
    Title: typeof import('./components/Interface/title.vue')['default']
    XContainer: typeof import('./components/Interface/XContainer.vue')['default']
  }
}
